services:
  # PostgreSQL Database
  tekera-db:
    image: postgres:latest
    container_name: tekera-db
    ports:
      - "5435:5432"  # Host portu ile container portunu eşliyoruz
    environment:
      - POSTGRES_USER=tekera_user
      - POSTGRES_PASSWORD=tekera_pass
      - POSTGRES_DB=tekera-db
    networks:
      - my-network
    volumes:
      - postgres_data:/var/lib/postgresql/data  # Veritabanı verilerini hostta sakla
    restart: unless-stopped  # Sistem yeniden başlarsa veri kaybolmaz

  # MongoDb Database
  tekera-document-db:
    image: mongo
    container_name: tekera-document-db
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: tekera_user
      MONGO_INITDB_ROOT_PASSWORD: tekera_pass

  # bin/elasticsearch-service-tokens create elastic/kibana kibana-token komut ile kibananın elastic e bağlanacağı tokeni oluşturur
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.13.4
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    ports:
      - "9200:9200"
    networks:
      - my-network

  kibana:
    image: docker.elastic.co/kibana/kibana:8.13.4
    container_name: kibana
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      - SERVER_SSL_ENABLED=false
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    networks:
      - my-network

  logstash:
    image: docker.elastic.co/logstash/logstash:8.13.4
    container_name: logstash
    ports:
      - "5000:5000"  # TCP log için
    volumes:
      - ./logstash:/usr/share/logstash/pipeline
    depends_on:
      - elasticsearch
    networks:
      - my-network

  # MinIO (Blob Storage)
  # mc alias set myminio http://localhost:9000 minioadmin minioadmin ile myminio alias oluştur
  # minio containerine gir mc anonymous set download myminio/tekera-bucket bu komut ile bucket i public yap
  minio1:
    image: minio/minio:latest
    container_name: minio1
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: tekera_user
      MINIO_ROOT_PASSWORD: tekera_pass
    volumes:
      - minio1_data:/data
    command: server --console-address ":9001" http://minio{1...4}/data
    networks:
      - my-network

  minio2:
    image: minio/minio:latest
    container_name: minio2
    environment:
      MINIO_ROOT_USER: tekera_user
      MINIO_ROOT_PASSWORD: tekera_pass
    volumes:
      - minio2_data:/data
    command: server http://minio{1...4}/data
    networks:
      - my-network

  minio3:
    image: minio/minio:latest
    container_name: minio3
    environment:
      MINIO_ROOT_USER: tekera_user
      MINIO_ROOT_PASSWORD: tekera_pass
    volumes:
      - minio3_data:/data
    command: server http://minio{1...4}/data
    networks:
      - my-network

  minio4:
    image: minio/minio:latest
    container_name: minio4
    environment:
      MINIO_ROOT_USER: tekera_user
      MINIO_ROOT_PASSWORD: tekera_pass
    volumes:
      - minio4_data:/data
    command: server http://minio{1...4}/data
    networks:
      - my-network

  mc-once:
    image: minio/mc
    depends_on:
      - minio1
    entrypoint: >
      sh -c "
          echo '🕒 MinIO hazır mı kontrol ediliyor...' &&
          until mc alias set myminio http://minio1:9000 tekera_user tekera_pass; do
            echo '⏳ Bekleniyor...'; sleep 2;
          done &&
          echo '✅ mc alias tamam.' &&

          mc mb myminio/tekera-bucket || true &&
          mc anonymous set download myminio/tekera-bucket &&
          echo '✅ Bucket public yapıldı.'
        "
    networks:
      - my-network
    restart: "no"

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: apache-kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
      - "29092:29092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,PLAINTEXT_HOST://0.0.0.0:29092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui
    ports:
      - "8180:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092
      KAFKA_CLUSTERS_0_ZOOKEEPER: zookeeper:2181
    depends_on:
      - kafka

  mind-generator-api:
    build:
      context: ../mind-generator
    container_name: mind-generator
    ports:
      - "3009:3009"
    networks:
      - my-network

#  tekera-api:
#    build:
#      context: .
#    container_name: arzuamber-api
#    depends_on:
#      - tekera-db
#      - minio1
#    ports:
#      - "9090:8080"
#    networks:
#      - my-network
#    restart: unless-stopped

volumes:
  postgres_data:
  minio1_data:
  minio2_data:
  minio3_data:
  minio4_data:

networks:
  my-network:
    driver: bridge  # Aynı ağda çalışan servisler birbirine erişebilsin