spring:
  application:
    name: tekera-marketplace

  servlet:
    multipart:
      enabled: true
      max-file-size: 20MB
      max-request-size: 20MB

  data:
    mongodb:
      uri: mongodb://tekera_user:tekera_pass@localhost:27017/tekera-document-db?authSource=admin

  datasource:
    driver-class-name: org.postgresql.Driver
    #url: jdbc:postgresql://arzuamber-db:5432/arzuamber-db
    url: jdbc:postgresql://localhost:5435/tekera-db
    username: tekera_user
    password: tekera_pass
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  minio:
    url: http://localhost:9000
    user: tekera_user
    password: tekera_pass
    bucket-name: tekera-bucket

  kafka:
    bootstrap-servers: localhost:29092
    consumer:
      properties:
        spring:
          json:
            trusted:
              packages: *
      group-id: tekeraGroup
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
#      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
    producer:
#      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

  mind-creator:
    api: http://host.docker.internal:3009/generate